package test.greenDAO.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import test.greenDAO.bean.Duty;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "things".
*/
public class DutyDao extends AbstractDao<Duty, Long> {

    public static final String TABLENAME = "things";

    /**
     * Properties of entity Duty.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Info = new Property(2, String.class, "info", false, "INFO");
        public final static Property Type = new Property(3, String.class, "type", false, "TYPE");
        public final static Property Status = new Property(4, Boolean.class, "status", false, "STATUS");
        public final static Property Date = new Property(5, java.util.Date.class, "date", false, "DATE");
        public final static Property Clocktime = new Property(6, Long.class, "clocktime", false, "CLOCKTIME");
        public final static Property Clockfanshi = new Property(7, Integer.class, "clockfanshi", false, "CLOCKFANSHI");
        public final static Property Clocktqtime = new Property(8, Integer.class, "clocktqtime", false, "CLOCKTQTIME");
        public final static Property City = new Property(9, String.class, "city", false, "CITY");
        public final static Property Weather = new Property(10, String.class, "weather", false, "WEATHER");
    };


    public DutyDao(DaoConfig config) {
        super(config);
    }
    
    public DutyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"things\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TITLE\" TEXT NOT NULL ," + // 1: title
                "\"INFO\" TEXT," + // 2: info
                "\"TYPE\" TEXT," + // 3: type
                "\"STATUS\" INTEGER," + // 4: status
                "\"DATE\" INTEGER," + // 5: date
                "\"CLOCKTIME\" INTEGER," + // 6: clocktime
                "\"CLOCKFANSHI\" INTEGER," + // 7: clockfanshi
                "\"CLOCKTQTIME\" INTEGER," + // 8: clocktqtime
                "\"CITY\" TEXT," + // 9: city
                "\"WEATHER\" TEXT);"); // 10: weather
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"things\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Duty entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getTitle());
 
        String info = entity.getInfo();
        if (info != null) {
            stmt.bindString(3, info);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(4, type);
        }
 
        Boolean status = entity.getStatus();
        if (status != null) {
            stmt.bindLong(5, status ? 1L: 0L);
        }
 
        java.util.Date date = entity.getDate();
        if (date != null) {
            stmt.bindLong(6, date.getTime());
        }
 
        Long clocktime = entity.getClocktime();
        if (clocktime != null) {
            stmt.bindLong(7, clocktime);
        }
 
        Integer clockfanshi = entity.getClockfanshi();
        if (clockfanshi != null) {
            stmt.bindLong(8, clockfanshi);
        }
 
        Integer clocktqtime = entity.getClocktqtime();
        if (clocktqtime != null) {
            stmt.bindLong(9, clocktqtime);
        }
 
        String city = entity.getCity();
        if (city != null) {
            stmt.bindString(10, city);
        }
 
        String weather = entity.getWeather();
        if (weather != null) {
            stmt.bindString(11, weather);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Duty readEntity(Cursor cursor, int offset) {
        Duty entity = new Duty( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // info
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // type
            cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0, // status
            cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)), // date
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6), // clocktime
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // clockfanshi
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // clocktqtime
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // city
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10) // weather
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Duty entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.getString(offset + 1));
        entity.setInfo(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setType(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setStatus(cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0);
        entity.setDate(cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)));
        entity.setClocktime(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
        entity.setClockfanshi(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setClocktqtime(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setCity(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setWeather(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Duty entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Duty entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
