package test.greenDAO.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "things".
 */
public class Duty implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String title;
    private String info;
    private String type;
    private Boolean status;
    private java.util.Date date;
    private Long clocktime;
    private Integer clockfanshi;
    private Integer clocktqtime;
    private String city;
    private String weather;

    public Duty() {
    }

    public Duty(Long id) {
        this.id = id;
    }

    public Duty(Long id, String title, String info, String type, Boolean status, java.util.Date date, Long clocktime, Integer clockfanshi, Integer clocktqtime, String city, String weather) {
        this.id = id;
        this.title = title;
        this.info = info;
        this.type = type;
        this.status = status;
        this.date = date;
        this.clocktime = clocktime;
        this.clockfanshi = clockfanshi;
        this.clocktqtime = clocktqtime;
        this.city = city;
        this.weather = weather;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    public String getInfo() {
        return info;
    }

    public void setInfo(String info) {
        this.info = info;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Boolean getStatus() {
        return status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public Long getClocktime() {
        return clocktime;
    }

    public void setClocktime(Long clocktime) {
        this.clocktime = clocktime;
    }

    public Integer getClockfanshi() {
        return clockfanshi;
    }

    public void setClockfanshi(Integer clockfanshi) {
        this.clockfanshi = clockfanshi;
    }

    public Integer getClocktqtime() {
        return clocktqtime;
    }

    public void setClocktqtime(Integer clocktqtime) {
        this.clocktqtime = clocktqtime;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getWeather() {
        return weather;
    }

    public void setWeather(String weather) {
        this.weather = weather;
    }

}
